export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const NEW_PRODUCT = 'NEW_PRODUCT'
export const FETCH_PROD_COMMENTS = 'FETCH_PROD_COMMENTS'
export const NEW_PROD_COMMENT = 'NEW_PROD_COMMENT'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGN_UP = 'SIGN_UP'